# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - i450-team7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://i450-team7.scm.azurewebsites.net/
        username: ${{ secrets.AzureAppService_ContainerUsername_93b8dce317b44c119601dfdb37a142ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3816911f444d4979833fe67bf90b7d27 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: i450-team7.scm.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_93b8dce317b44c119601dfdb37a142ee }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'i450-team7'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_99627287f24e4cef91333bec4926588e }}
        images: 'i450-team7.scm.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_93b8dce317b44c119601dfdb37a142ee }}/appsvc/wordpress-alpine-php:${{ github.sha }}'